### ISSUE TITLE
Can't get multiple chemical shifts in loop method

### ISSUE THREAD

**Issue by kumar-physics** [uwbmrb/BMRB-API#20]
Entry 18857 has 33 chemical shift lists. When I try
`{
    "method": "loop",
    "jsonrpc": "2.0",
    "params": {
        "ids": [18857],
        "keys": ["_Atom_chem_shift"]
    },
    "id": 1
}`
I get only one chemical shift list. Is it a bug or is this the way the query works?

**Comment by jonwedell** [comment]
I just tested your example and I get all 33 lists.

```python
a = json_test.postIt("loop", { "ids": [18857], "keys": ["_Atom_chem_shift"] })
>>> len(a['result']['18857']['_Atom_chem_shift'])
33
>>> a['result']['18857']['_Atom_chem_shift'][0]
[u'category', u'data', u'tags']
>>> a['result']['18857']['_Atom_chem_shift'][0]['data'][0]
[u'1', u'.', u'1', u'1', u'1', u'1', u'MET', u'HA', u'H', u'1', u'4.141', u'0.002', u'.', u'1', u'.', u'.', u'.', u'.', u'1', u'MET', u'HA', u'.', u'18857', u'1']
>>> a['result']['18857']['_Atom_chem_shift'][32]['data'][0]
[u'1', u'.', u'1', u'1', u'1', u'1', u'MET', u'HA', u'H', u'1', u'4.101', u'0.002', u'.', u'1', u'.', u'.', u'.', u'.', u'1', u'MET', u'HA', u'.', u'18857', u'33']
```

With that query type, `a['result']['18857']['_Atom_chem_shift']` points to a list. Each element of the list is a dictionary that corresponds to the JSON representation of a loop.

**Comment by kumar-physics** [comment]
Thanks. Its my mistake. I had the data in the variable, but didn't realise how to access it. Now I know how to access it.
