### ISSUE TITLE
Write method to pull up simulated HSQC spectrum

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/BMRB-API#28]

**Comment by kumar-physics** [comment]
I have the script in PyBMRB. If you want you may add it to PyNMRSRTAR.

**Comment by jonwedell** [comment]
Implemented earlier this year: https://webapi.bmrb.wisc.edu/current/entry/15000/simulate_hsqc

Kumaran, my apologies I took so long to get this in there. If you want me to build other PyBMRB visualizations into the API, I'll get on it right away.
