### ISSUE TITLE
Error: Entry does not exist in the public database

### ISSUE THREAD

**Issue by lucubrator** [uwbmrb/BMRB-API#45]
I use the following query to obtain a list of all entries containing at least one RNA entity:
`current/search/get_id_by_tag_value/Entity.Polymer_type/polyribonucleotide` 
 
One of the returned entry IDs is `34265`.

Strangely enough, I get an error when trying to download this entry using the `entry` query:
`http://webapi.bmrb.wisc.edu/current/entry/34265`

This is the returned json object string:
`{"error":"Entry '34265' does not exist in the public database."}`

Is this a bug? If not, I need some input on how to properly handle these cases:

1. What exactly does this message mean? I see that `/current/entry/ThisIsNotAnEntryID` returns the same message. Does it mean anything else than simply that the entry cannot be found?
2. Does this particular entry exist? It isn't in the list of all entries (`current/list_entries`).
3. If it does, will such an entry become availible through the public data base eventually?

**Comment by jonwedell** [comment]
What has happened here is that our relational database has updated more recently than the entry database, and therefore you are seeing that entry number in the one query type and not the other. The databases are supposed to be updated in tandem, so there is definitely something that has gone wrong. @dmaziuk - has the schedule of the DB loader changed?

As the two databases don't update completely atomically (one is a relational database and the other is a Redis instance with the actual entry contents) it would make sense to have code to handle this case in the off chance you happen to query the server during an update. That being said, the entry should become available through the other API methods shortly.

I've manually trigger an update and that entry is now available. Thanks for the report!

**Comment by lucubrator** [comment]
Great. Many thanks for the information and for the update!

**Comment by jonwedell** [comment]
We've updated the DB reload scripts to ensure that both fire back-to-back. There should only be a few minutes each week where there could be a discrepancy between them. Thanks again for the report!
