### ISSUE TITLE
Pressure Category

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRB-API#47]
In sample conditions the pressure category is pre-filled with a value of ambient and units of atm. When annotating this is always changed to a value of 1 and the units remaining as atm. This pre-fill could be changed to 1 rather than ambient to save time later down the line.

**Comment by jonwedell** [comment]
This issue is valid but lives in the API code rather than the frontend code. Fix implemented, it should be as suggested for new entries.

**Comment by jonwedell** [comment]
@rsiegl  - please confirm.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
