### ISSUE TITLE
Multiple RNA strands in single entry

### ISSUE THREAD

**Issue by lucubrator** [uwbmrb/BMRB-API#49]
How is the following case handled: multiple (2 or more) _unique_ RNA strands (e.g. a duplex) in a single BMRB STAR-file?

I have seen that in the case of ``strand_A`` and ``strand_B`` being identical, both components/strands will point to the same ``Entity_ID``, but will have unique ``_Entity_assembly.ID``s: 
```
   loop_
      _Entity_assembly.ID
      _Entity_assembly.Entity_assembly_name
      _Entity_assembly.Entity_ID
      _Entity_assembly.Entity_label
         ...
         1   'RNA duplex, chain 1'   1   $N-6_Methyl_Adenosine_RNA ...
         2   'RNA duplex, chain 2'   1   $N-6_Methyl_Adenosine_RNA ...
   stop_
```
and in the ``entity`` category/section, only 1 entity is listed:
```
loop_
      _Entity_poly_seq.Hetero
      _Entity_poly_seq.Mon_ID
      _Entity_poly_seq.Num
      _Entity_poly_seq.Comp_index_ID
      _Entity_poly_seq.Entry_ID
      _Entity_poly_seq.Entity_ID
     .   G     1    1    25220   1    
     .   G     2    2    25220   1    
     .   6MD   3    3    25220   1    
     .   C     4    4    25220   1    
     .   U     5    5    25220   1    
     .   A     6    6    25220   1    
     .   G     7    7    25220   1    
     .   U     8    8    25220   1    
     .   C     9    9    25220   1    
     .   C     10   10   25220   1    
   stop_
``` 

How is ``strand_A`` =/= ``strand_B`` handled?

**Comment by kumar-physics** [comment]
If strand_A is not equal to strand_B then they are different entities. They will get different entity_IDs. For example homodimer vs hetrodimer. Homodimer has one entity and hetrodimer has two entities.

**Comment by jonwedell** [comment]
Indeed, as Kumaran said you will need to have multiple "entity" saveframes - one for each unique strand.
