### ISSUE TITLE
remove Entry.Entry_ID DB columns

### ISSUE THREAD

**Issue by dmaziuk** [uwbmrb/BMRB-API#53]
currently added by `initialize.sql`.

Will need to make sure every query uses `if table == "Entry" then join on "ID" else join on "Entry_ID"` condition when making joins. 

The problem is if/when we phase out the old databases and start using this to generate CSV dumps for people to download, they will not match our "official" schema aka the dictionary.

**Comment by jonwedell** [comment]
Implemented a long time ago.
