### ISSUE TITLE
nmrstar format removed?

### ISSUE THREAD

**Issue by hobofan** [uwbmrb/BMRB-API#54]
I noticed that the link from the docs for the `nmrstar` format (http://webapi.bmrb.wisc.edu/v2/entry/15000?format=nmrstar) leads to an error response.

It looks like the `nmrstar` format has been removed. If so it probably would be good to also remove it from the docs.

**Comment by jonwedell** [comment]
Thank you for bringing this to my attention. Yes, the `nmrstar` format was removed as we didn't think that was a reasonable way to serve the data, and furthermore the name `nmrstar` was misleading for an endpoint that technically returns JSON format data with NMR-STAR embedded inside of it. I have updated the documentation to match.
