### ISSUE TITLE
BMRB status - All of the BMRB down

### ISSUE THREAD

**Issue by lucubrator** [uwbmrb/BMRB-API#56]
Both the FTP (www.bmrb.wisc.edu/ftp/pub/bmrb/entry_lists/nmr-star3.1/ which now redirect to www.bmrb.io/ftp/pub/bmrb/entry_lists/nmr-star3.1/) and the API (www.webapi.bmrb.wisc.edu/current/ --> www.api.bmrb.io/) seem to be down. Even the main page of the BMRB (www.bmrb.wisc.edu --> https://bmrb.io/) also seems to be down. 

Are you aware of this? Is this a planned maintenance/restart? It worked earlier today.

**Comment by lucubrator** [comment]
@dmaziuk @jonwedell

**Comment by dmaziuk** [comment]
It's sitting in UConn Health VM infrastructure now, both Jon and I are in Wisconsin. So our options are a bit limited I'm afraid. FWIW the hostnames don't seem to resolve from here either so I can't get into the VMs ATM.

**Comment by jonwedell** [comment]
Yeah, it appears to be a major system failure at UConn. We've notified the admins and are waiting for news.

**Comment by jonwedell** [comment]
@lucubrator - Service restored. We're still waiting to hear back about exactly what went wrong. Thanks for your patience!

**Comment by lucubrator** [comment]
Thank you for the information. It's working again from my side as well!
